version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/NEON.Trader.Desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nuget-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
